config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  get 'academic_record', to: 'pages#academic_record'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
    resources :units, only: [:new, :create]
  end
  resources :enrollments, only: :index
  resources :units, only: [:show, :edit, :update, :destroy] do
    resources :activities, only: [:new, :create, :index]
    resources :activities, only: [] do
      collection do
        get ':type', to: 'activities#get_by_type', as: :get_by_type
      end
    end
  end
  resources :activities, except: [:new, :create,:index] do
    resources :solutions, only: :create
  end
  resources :solutions, only: [:index, :show, :update]
end

app/models/activity.rb
class Activity < ApplicationRecord
  enum activity_type: { clase: 'clase', ejercicio: 'ejercicio', recurso: 'recurso' }, _prefix: true
  belongs_to :unit
  has_one_attached :file
  has_many :solutions, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :file, presence: true
  validates :activity_type, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_one_attached :course_img
  has_many :enrollments, dependent: :destroy
  has_many :units, dependent: :destroy
  validates :name, presence: true
  has_many :solutions, through: :units
  has_many :activities, through: :units
  has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student, class_name: "User", foreign_key: "user_id"
  belongs_to :course
  has_many :solutions
  validates :student,
            uniqueness: { scope: :course, message: "a student can only register one time for a course" }
end

app/models/solution.rb
class Solution < ApplicationRecord
  after_commit :update_final_grade
  belongs_to :enrollment
  belongs_to :activity
  has_one_attached :file
  validates :activity,
            uniqueness: { scope: :enrollment, message: "a user can only have a unique solution per activity" }
  validates :file, :activity, :enrollment, presence: true

  private

  def update_final_grade
    solutions = enrollment.solutions.where.not(score: nil)
    if solutions.empty?
      enrollment.update(final_grade: nil)
    else
      scores = solutions.to_a.map { |s| s.score }
      sum = scores.inject(:+)
      final_grade = sum / scores.size
      enrollment.update(final_grade: final_grade)
    end
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :course
  has_one_attached :unit_img
  has_many :activities, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  has_many :solutions, through: :activities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :enrollments, dependent: :destroy
  has_one_attached :avatar
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show update destroy]

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.unit = Unit.find(params[:unit_id])
    if @activity.valid?
      @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def get_by_type
    if Activity.activity_types.keys.include?(params[:type])
      @activities = Activity.where(activity_type: params[:type], unit: params[:unit_id])
    else
      @activities = []
    end
  end

  def show
    @solution = @activity.solutions.joins(:enrollment).find_by(enrollment: { student: current_user })
    @done = @solution.blank?
    @solution ||= Solution.new
  end

  def update
  end

  def index
    redirect_to new_unit_activity_path(params[:unit_id])
  end

  def edit
  end

  def destroy
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :description, :file, :activity_type)
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user! ## esta accion indica que user debe estar logueado puede estar en cualquier controller



  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name avatar teacher])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name avatar teacher])
  end



end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: :show
  def index
    @courses = Course.all
  end

  def show
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def index
    @enrollments = Enrollment.all
    @solutions = Solution.all
    @users = User.all
  end

  def create
    @enrollment = Enrollment.create(course_id: params[:course_id], student: current_user)
    redirect_to course_path(params[:course_id])
  end

  private

  def enrollment_params
    params.require(:enrollment).permit(:final_grade)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    # user_signed_in? ? redirect_to(courses_path) : redirect_to(new_user_session_path)
  end

  def academic_record
    @courses = Course.all
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :set_solution, only: %i[update show]
  def index
    redirect_to root_path unless current_user.teacher
    @courses = Course.all
  end

  def show
    redirect_to root_path unless current_user.teacher
  end

  def create
    @activity = Activity.find(params[:activity_id])
    @enrollment = @activity.unit.course.enrollments.find_by(student: current_user)
    @solution = Solution.new(solution_params)
    @solution.activity = @activity
    @solution.enrollment = @enrollment
    @solution.save
    redirect_to activity_path(@activity)
  end

  def update
    @solution.update(solution_params)
    redirect_to solutions_path
  end

  private

  def solution_params
    params.require(:solution).permit(:score, :file, :comment)
  end

  def set_solution
    @solution = Solution.find(params[:id])
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :update, :destroy]
  def new
  end

  def show

  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def unit_params
    params.require(:unit).permit(:title, :description)
  end

  def set_unit
    @unit = Unit.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/get_by_type.html.erb
<div class="container">
  <div class="card my-4">
    <div class="card-header bg-info rounded">
      <h1 class="text-light text-center"><%= params[:type].capitalize %>s</h1>
    </div>
  </div>
  <div class="container activities grid">
    <% @activities.each do |a| %>
      <div class="g-col-4">
        <%= link_to a, style:"text-decoration: none;color: white" do %>
          <div class="course card bg-info d-flex h-100">
            <div class="card-header flex-grow-1 d-flex flex-column justify-content-center align-items-center">
              <% unless current_user.teacher %>
                <% if a.activity_type_ejercicio? %>
                  <% if a.solutions.joins(:enrollment).find_by(enrollment: { student: current_user }).blank? %>
                    <span><i class="fas fa-circle" style="color:red"></i> Pendiente</span>
                  <% else %>
                    <span><i class="fas fa-check" style="color:green"></i> Hecho</span>
                  <% end %>
                <% end %>
              <% end %>
              <h3 class="text-center"><%= a.title %></h3>
            </div>
            <div class="card-body text-center flex-grow-0 " style="height:min-content;">
              <%= a.activity_type_clase? ? cl_image_tag(a.file.key,:transformation=>[
              {:width=>550, :crop=>"scale"},
              {:fetch_format=>:auto}
              ], class:'w-75 my-3 rounded', :resource_type=>"video") : cl_image_tag(a.file.key,:transformation=>[
              {:width=>550, :crop=>"scale"},
              {:fetch_format=>:auto}
              ], class:'w-75 my-3 rounded')%>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% if current_user.teacher %>
      <div class="g-col-4">
        <%= link_to new_unit_activity_path(params[:unit_id]) , style:"text-decoration: none;color: white" do %>
          <div class="course card bg-info d-flex h-100">
            <div class="card-header flex-grow-0 d-flex flex-column justify-content-center align-items-center">
              <h3 class="text-center">Crear Actividad</h3>
            </div>
            <div class="card-body flex-grow-1 d-flex justify-content-center align-items-center" style="height:min-content;">
              <%=  cl_image_tag("v1644591561/new_file_white_wvqzrq.svg",:transformation=>[
              {:width=>550, :crop=>"scale"},
              {:fetch_format=>:auto}
              ], class:'w-75 my-3 rounded')%>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container pt-3">
  <h2 class="mt-3 mb-5">Crear Actividad</h2>

  <%= simple_form_for( @activity , url: unit_activities_path(params[:unit_id]) ,wrapper: :floating_labels_form,
    wrapper_mappings: {
      select:        :floating_labels_select
    },defaults: { wrapper_html: { class: "form-floating mb-4" },placeholder:' ' }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  required: true,
                  autofocus: true %>
      <%= f.input :description,
                  required: true %>
      <label for="activity_type" class="my-3">Elige el tipo de actividad </label>
      <%= f.input :activity_type , collection: ['clase','ejercicio','recurso'], input_html: { id: 'activity_type' } , label: false , required:true %>
      <label for="file_activity" class="my-3">Subir Material de la Actividad </label>
      <%= f.input :file , label: false%>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Crear" ,class:'btn btn-primary'%>
    </div>
  <% end %>

</div>

app/views/activities/show.html.erb
<div class="container">
  <div class="d-flex flex-row m-3 align-items-center justify-content-around">
    <div class="activity-show-details " style="width:72%">
      <div class="card bg-warning w-100">
        <div class="card-header">
          <% unless current_user.teacher %>
            <% if @activity.activity_type_ejercicio? %>
              <% if @done %>
                <p><i class="fas fa-circle" style="color:red"></i> Pendiente</p>
              <% else %>
                <p><i class="fas fa-check" style="color:green"></i></i> Hecho</p>
              <% end %>
            <% end %>
          <% end %>
          <h2><%= @activity.title %></h2>
        </div>
        <div class="card-body">
          <p><%= @activity.description %></p>
        </div>
      </div>
      <div class="file-preview d-flex justify-content-center">
        <% if @activity.activity_type_ejercicio? %>
        <!-- Button trigger modal -->
          <button type="button" class="btn btn-warning my-4 w-50" data-bs-toggle="modal" data-bs-target="#activity_file">
            <%= cl_image_tag(@activity.file.key,:transformation=>[
              {:width=>550, :crop=>"scale"},
              {:fetch_format=>:auto}
              ], class:'w-100 rounded') %>
          </button>
          <!-- Modal -->
          <div class="modal fade" id="activity_file" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog" style="width:50vw;max-width:50vw">
              <div class="modal-content">
                <div class="modal-header">
                  <%= link_to  @activity.file, class:'btn btn-secondary mr-3' do%>
                    <i class="fas fa-external-link-alt"></i>
                  <% end %>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <iframe
                  class="w-100"
                  style="height:60vh;"
                  src=<%= cloudinary_url(@activity.file.key, :format => "pdf") %>></iframe>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <% if @activity.activity_type_clase? %>
          <div class="btn btn-warning my-4" style="width:85%">
            <video controls width="100%">
              <source src="<%= url_for(@activity.file) %>"
                      type="video/mp4">
              Sorry, your browser doesn't support embedded videos.
            </video>
          </div>
        <% end %>
      </div>
    </div>
    <% unless current_user.teacher %>
      <% if @activity.activity_type_ejercicio? %>
        <% if @done %>
          <div class="card border-primary " style="width:24%">
            <div class="card-header bg-primary text-light">
              <h3>Tu Trabajo</h3>
            </div>
            <div class="card-body text-dark">
              <%= simple_form_for @solution, url: activity_solutions_path(params[:id]), html: {id: "solution_form"} ,defaults: { wrapper_html: { class: "form-floating mb-3" }} do |f| %>
                <span>Seleccione su archivo</span>
                <%= f.input :file ,input_html: { class: 'solution'}, label: false, direct_upload: true%>
                <%= f.submit 'Subir Solucion', class:'btn btn-primary'%>
              <% end %>
            </div>
          </div>
        <% else %>
          <% if @solution.score.blank? %>
            <div class="card border-primary " style="width:24%" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" title="Sin Calificar" data-bs-custom-class="text-center" data-bs-content="Tu trabajo todavia no ha sido calificado, porfavor consulta con el profesor a cargo.">
          <% else %>
            <div class="card border-primary " style="width:24%">
          <% end %>
            <div class="card-header bg-primary text-light">
              <h3>Tu Trabajo</h3>
            </div>
            <div class="card-body text-dark text-center">
              <div class="form-floating mb-3">
                <input type="number" name="solution[score]" id="solution_score" <%= raw("value=#{@solution.score}") unless @solution.score.blank? %> form="solution_form" placeholder=' ' class="form-control" disabled>
                <label for="solution_score">Nota</label>
              </div>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#solution_file">
                <%= cl_image_tag(@solution.file.key,:transformation=>[
                {:width=>550, :crop=>"scale"},
                {:fetch_format=>:auto}
                ], class:'w-100 rounded') %>
              </button>

              <!-- Modal -->
              <div class="modal fade" id="solution_file" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog" style="width:50vw;max-width:50vw">
                  <div class="modal-content">
                    <div class="modal-header">
                      <%= link_to  @solution.file, class:'btn btn-secondary mr-3' do%>
                        <i class="fas fa-external-link-alt"></i>
                      <% end %>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <iframe
                      class="w-100"
                      style="height:60vh;"
                      src=<%= cloudinary_url(@solution.file.key, :format => "pdf") %>></iframe>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-floating mb-3">
                <input type="text" name="solution[comment]" id="solution_comment" <%= raw("value='#{@solution.comment}'") unless @solution.comment.blank? %> form="solution_form" placeholder=' ' class="form-control" disabled>
                <label for="solution_comment">Comentario</label>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/courses/index.html.erb
<div class="container pt-3">
  <% @courses.each do |c| %>
    <a href="<%= url_for(c) %>" style="text-decoration: none;color: white">
      <div class="course card my-3 bg-info">
        <div class="card-header">
          <h3><%= image_tag c.course_img , class:'shadow avatar-medium ms-5 me-3'%><%= c.name %></h3>
        </div>
        <div class="card-body">
          <h4 class="ms-5">Actividades:</h4>
          <div class="d-flex justify-content-evenly">
            <p class="text-center fs-4">Clases: <%= c.activities.activity_type_clase.count %></p>
            <p class="text-center fs-4">Ejercicios: <%= c.activities.activity_type_ejercicio.count %></p>
            <p class="text-center fs-4">Recursos: <%= c.activities.activity_type_recurso.count %></p>
          </div>
        </div>
        <div class="card-footer">
          <% unless current_user.teacher %>
            <p class="text-center fs-6"><%= ejercicios_pendientes = c.activities.activity_type_ejercicio.joins("LEFT OUTER JOIN (#{Solution.joins(:enrollment).where(enrollment:{student: current_user}).to_sql}) AS result  ON activities.id = result.activity_id").where("result.id IS NULL").count %> ejercicio<%= ejercicios_pendientes==1 ? '' : 's' %> por resolver</p>
          <% end %>
        </div>
      </div>
    </a>
  <% end %>
</div>

app/views/courses/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header bg-primary rounded">
      <h1 class="text-light"><%= image_tag @course.course_img , class:'shadow avatar-medium me-3'%><%= @course.name %></h1>
    </div>
  </div>
  <div class="container units pt-4">

    <div class="container">
      <% @course.units.each do |u| %>
        <% unless Enrollment.find_by(course: @course,student:current_user).blank? && !current_user.teacher %>
          <a href="<%= url_for(u) %>" style="text-decoration: none;color: black">
        <% end %>
            <div class="unit card my-3 bg-warning">
              <div class="card-header">
                <h3><%= image_tag u.unit_img , class:'shadow avatar-medium ms-5 me-3'%><%= u.title %></h3>
              </div>
              <div class="card-body">
                <h4 class="ms-5">Actividades:</h4>
                <div class="d-flex justify-content-evenly">
                  <p class="text-center fs-4">Clases: <%= u.activities.activity_type_clase.count %></p>
                  <p class="text-center fs-4">Ejercicios: <%= u.activities.activity_type_ejercicio.count %></p>
                  <p class="text-center fs-4">Recursos: <%= u.activities.activity_type_recurso.count %></p>
                </div>
              </div>
              <div class="card-footer">
                <% unless current_user.teacher %>
                  <p class="text-center fs-6"><%= ejercicios_pendientes = u.activities.activity_type_ejercicio.joins("LEFT OUTER JOIN (#{Solution.joins(:enrollment).where(enrollment:{student: current_user}).to_sql}) AS result  ON activities.id = result.activity_id").where("result.id IS NULL").count %> ejercicio<%= ejercicios_pendientes==1 ? '' : 's' %> por resolver</p>
                <% end %>
              </div>
            </div>
        <% if Enrollment.find_by(course: @course,student:current_user).blank? && !current_user.teacher %>
          </a>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <% if Enrollment.find_by(course: @course,student:current_user).blank? && !current_user.teacher%>
      <%= button_to 'Matriculate', course_enrollments_path(params[:id]),method: :post, class:"btn btn-danger my-3 fs-4" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb-->

<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>AprendeYa!</title>
    <link rel="icon"
      type="image/png"
      href="https://i.ibb.co/x1qg1zh/LOGO-PNG-APRENDE-YA.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <!-- This refers to app/javascript/stylesheets/application.scss-->
    <%# <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light d-flex flex-column h-100">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


    <main class="flex-shrink-0"><%= yield %></main>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <footer class="footer mt-auto">
    <div class="container d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top ">
      <div class="col-md-4 d-flex align-items-center">
        <span class="text-muted fw-bold" style="white-space:nowrap;">© 2022 AprendeYa!, Inc</span>
      </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a href="#"><i class="fab fa-instagram fs-3"></i></a></li>
        <li class="ms-3"><a href="#"><i class="fab fa-facebook fs-3"></i></a></li>
        <li class="ms-3"><a href="#"><i class="fab fa-twitter fs-3"></i></a></li>
      </ul>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
<div class="container">
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-1 border-bottom bg-light">
    <a href="<%= root_path %>" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-white text-decoration-none">
      <img src="https://i.ibb.co/x1qg1zh/LOGO-PNG-APRENDE-YA.png" style= "width: 7vw" class= "navbar-brand" alt="">
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><%= link_to "Home", root_path, class: "nav-link px-2 link-secondary" %></li>
      <li><%= link_to "Cursos", courses_path, class: "nav-link px-2 link-secondary" %></li>
      <% if user_signed_in? %>
        <li>
          <% if current_user.teacher %>
            <%=  link_to "Soluciones", solutions_path, class: "nav-link px-2 link-secondary" %>
          <% else %>
            <%= link_to "Notas", academic_record_path, class: "nav-link px-2 link-secondary"%>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="col-md-3 text-end">
      <% if user_signed_in? %>
        <div class="flex-shrink-0 dropdown">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar , class:"avatar" %>
            <% else %>
              <i class="fa fa-user-secret fa-2x"></i>
            <% end %>
          </a>
          <ul class="dropdown-menu text-small shadow dropdown-menu-end" aria-labelledby="dropdownUser2" style="">
            <li><%= link_to "Historial Academico", academic_record_path, class:"dropdown-item"%></li>
            <li><%= link_to "Editar Usuario", edit_user_registration_path, class:"dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Salir", destroy_user_session_path, method: :delete ,class:"dropdown-item"%></li>
          </ul>
        </div>
      <% else %>
        <%= link_to "Inicia aquí", user_session_path, class: "btn btn-primary" %>
        <%= link_to "Registrate", new_user_registration_path, class: "btn btn-outline-primary me-2" %>
      <% end %>
    </div>
  </header>
</div>

app/views/units/show.html.erb
<div class="container">
  <div class="card bg-info my-5">
    <div class="card-header rounded">
      <h2><%= @unit.title %></h2>
    </div>
    <div class="card-body  rounded">
      <p><%= @unit.description %></p>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col">
        <a href="<%= get_by_type_unit_activities_path(@unit, "clase") %>" style="text-decoration: none;color: white">
          <div class="activity_type card my-3 bg-warning">
            <img src="https://images.squarespace-cdn.com/content/v1/53aadf1de4b0a0a817640cca/1543441296303-5DFSRW22S9L7FKHZSGQX/bigstock-Pupils-And-Teacher-In-Classroo-254321620.jpg" class="card-img-top" alt="..." style="height:25vh;">
            <div class="card-body">
              <h4 class="text-center card-text">Clases</h4>
            </div>
          </div>
        </a>
      </div>
      <div class="col">
        <a href="<%= get_by_type_unit_activities_path(@unit, "ejercicio") %>" style="text-decoration: none;color: white">
          <div class="activity_type card my-3 bg-warning">
            <img src="http://previews.123rf.com/images/gorelova/gorelova0908/gorelova090800019/5421842-El-chico-divertido-hacer-la-tarea-Foto-de-archivo.jpg" class="card-img-top" alt="..." style="height:25vh;" >
            <div class="card-body">
              <h4 class="text-center card-text">Ejercicios</h4>
            </div>
            <% unless current_user.teacher %>
              <% ejercicios_pendientes = @unit.activities.activity_type_ejercicio.joins("LEFT OUTER JOIN (#{Solution.joins(:enrollment).where(enrollment:{student: current_user}).to_sql}) AS result  ON activities.id = result.activity_id").where("result.id IS NULL").count %>
              <% if ejercicios_pendientes > 0%>
                <div class="card-footer bg-danger">
                  <p class="text-center"><%= ejercicios_pendientes %> ejercicio<%= ejercicios_pendientes==1 ? '' : 's' %> por resolver</p>
                </div>
              <% end %>
            <% end %>
          </div>
        </a>
      </div>
      <div class="col">
        <a href="<%= get_by_type_unit_activities_path(@unit, "recurso") %>" style="text-decoration: none;color: white">
          <div class="activity_type card my-3 bg-warning">
            <img src="http://www.ugelcrucero.edu.pe/wp-content/uploads/2019/12/documentos-diagrama-finanzas_48369-1202.jpg" class="card-img-top" alt="..." style="height:25vh;">
            <div class="card-body">
              <h4 class="text-center card-text">Recursos</h4>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>